### ISSUE TITLE
Change UART

### ISSUE THREAD

**Issue by Belayasmert** [hcrest/sh2-demo-nucleo#1]
Hello,
thank you for the code! Everything worked well, but now i want to send my data to a HC-05 bluetooth device. Therefore i want to use the USART1 with PIN PA9(USART1_Tx) and PB7(USART1_Rx). But what do i need to change ? I tried to change the consoleUART to huart1 and the USART2 to USART1. But i am receiving no data on my other bluetooth device. I wrote a example code to test the BT devices and i received every data! I have to use HAL_UART_Transmit funcion but your code uses printf for the output. I cant get it working. Do you have any idea?

regards
Walter

**Comment by DaveOfThings** [comment]
Walter,

On the Nucleo F411 board, USART2 is wired to connect to the host PC through the USB.  That’s why we used that device for the console and I don’t think you want to change that.

To communicate with your Bluetooth device it sounds like you are on the right track trying to use USART1 with PA9 and PA7.  You’ll need to configure the GPIO pins and the USART device using the ST library functions (See HAL_GPIO_Init and HAL_UART_Init).  Then you can read and write using HAL_UART_Transmit and HAL_UART_Receive, etc.

If you look in the file uart_hal.c you’ll find some example code I wrote to let the STM32F411 talk to the BNO080 via USART1.  But the example is kind of complicated, using interrupts and DMA.  So you probably don’t want to use most of it but it might get you started writing your own code to use USART1.

Dave Wheeler
