### ISSUE TITLE
Remove persist tare settings from the flash of BNO080

### ISSUE THREAD

**Issue by ShanAJNA** [hcrest/sh2-demo-nucleo#13]
Hi, 

I have an application where in I save the orientation details using the setTareNow & persistTare commands. However, I want to now get rid of those tare values. I tried using clearTare() but it seems that it will only clear the settings for an instance. On power up, I am still getting the tared values. 

Please help. Thanks.

![image](https://user-images.githubusercontent.com/97172621/182379031-f18f6b52-d671-4378-a04c-305a6136f1e9.png)

![image](https://user-images.githubusercontent.com/97172621/182379170-1c2096cc-85fc-4fa4-97a9-1d035d883c17.png)

**Comment by dwheeler-ceva** [comment]
In the second block of code, the sh2_clearTare and sh2_setReorientation(0) do the same thing - they undo a previous tare setting, including one that was restored at power-up from a previous persistTare().  But neither one will affect the persisted tare.

If you want to get rid of the previously persisted tare, you should perform the sh2_clearTare() operation followed by another sh2_persistTare().

**Comment by ShanAJNA** [comment]
I tried that & it works. Thanks @dwheeler-ceva!
