### ISSUE TITLE
GetProductID Problem 

### ISSUE THREAD

**Issue by ldelmont** [hcrest/sh2-demo-nucleo#2]
I have a problem to obtain de Product ID, when i call the function getProdIdStart the value of the channel is still 0xFF. I don't understand what is wrong or what i have to modify ?

**Comment by DaveOfThings** [comment]
When you call sh2_open(), does it return 0 (SH2_OK)?  One of the tasks of open() is to establish communications with the chip and set the channel from 0xFF to the real value.

My guess is that communications between BNO080 and host are not working and sh2_open() is failing.  You’ll need to address the problem in your SH2 HAL implementation.

Dave Wheeler

**Comment by ldelmont** [comment]
Yes, it return SH2_OK. I am using the same function of the git project but with stm32l010rb microcontroller. Now , I am thinking that the problem is with the timer, because I have a 16 bits timer. I have modified many constants values with respect delays but still I have not found a correct way.


Lucas Adrian Delmonte

**Comment by ldelmont** [comment]
Hi Dave , now the channel is correct but when sh2_getProdIds is call  it doesn't go out of this loop of the function opProcess(pSh2, &getProdIdOp);

> `// While op not complete and not timed out.

    while ((pSh2->pOp != 0) &&
           ((pOp->timeout_us == 0) ||
            ((now_us-start_us) < pOp->timeout_us))) {
        // Service SHTP to poll the device.
        shtp_service(pSh2->pShtp);

        // Update the time
        now_us = pSh2->pHal->getTimeUs(pSh2->pHal);
}`

Do you have any idea of the problem?  or what i should check ?

Thanks, Lucas

**Comment by kzger** [comment]
> Hi Dave , now the channel is correct but when sh2_getProdIds is call it doesn't go out of this loop of the function opProcess(pSh2, &getProdIdOp);
> 
> > `// While op not complete and not timed out.
> 
> ```
> while ((pSh2->pOp != 0) &&
>        ((pOp->timeout_us == 0) ||
>         ((now_us-start_us) < pOp->timeout_us))) {
>     // Service SHTP to poll the device.
>     shtp_service(pSh2->pShtp);
> 
>     // Update the time
>     now_us = pSh2->pHal->getTimeUs(pSh2->pHal);
> ```
> 
> }`
> 
> Do you have any idea of the problem? or what i should check ?
> 
> Thanks, Lucas

Hi, @ldelmont and @dave20874.

Have you solved the problem? 

I have same issue too.

**Comment by dwheeler-ceva** [comment]
@kzger,

When the code is in this loop, the host is waiting for a response from the device.  If you're stuck here, that usually means basic communications are not working.  My advice would be to connect a logic analyzer to the I2C, SPI or UART lines to see what's happening.  You may also want to probe the interrupt line and check the states of the reset, PS0, and PS1 lines.  If you can't do that or you're stuck, can you provide more details on the type of interface and host you're using?

Dave

**Comment by kzger** [comment]
@dwheeler-ceva 

Thanks for responding.

I am using stm32F72x series to communicate bno080 via SPI1.

Already tried to replace interrupt pin with gpio_input pin, and read that pin with GPIO_ReadPin inside main loop, unfortunately, still no luck.

**Comment by dwheeler-ceva** [comment]
Do you have a logic analyzer, like a Saleae Logic unit, that you can use to see the SPI bus?  Some things to check: Is the WAKEN signal being asserted to the bno080?  Is the INTN signal being asserted by by bno080 to the device?  Is CSN being asserted to the device before the SPI transaction?    Do the SPI clock and data lines toggle as expected?

**Comment by kzger** [comment]
@dwheeler-ceva

Thanks for your advice.

The problem have been solved by increase more delay time to wait bno080 to respond.
